### ISSUE TITLE
Thanks for this.

### ISSUE THREAD

**Issue by bandidom9** [ginoledesma/sunpower-pvs-exporter#1]
I just got my panels turned on today. I currently have a rasberry pi running influxdb and grafana getting data from my hubitat. I would love to get this going to and gatter data directly from the PVS. Any way to contact you if I get stuck?

**Comment by ginoledesma** [comment]
Sure thing! You can reach me at gledesma (at) gmail (dot) com.

Let me know if you run into any issues — I've only tested this with my setup:
- Supervisor: PVS6
- Panels: SPR-E320-327-E-AC panels
- Micro-inverters: Enphase IQ7XS-96-ACM-U

**Comment by kskenyon** [comment]
Works perfectly on a PVS5 and a stock raspberry pi 3B+ between SunPower LAN 1 and WiFi.  Sending direct to a remote InfluxDB server through Prometheus-pushgateway and Prometheus.  27 SunPower 350 panels with micro-inverters. Easy peasy.
 
However, I can't access the pi through a VPN because it defaults to the pi ethernet port (eth0) and wlan0 doesn't see it.  I know there is a way to change the priority on ifconfig but I have to dig into that.  I have the same issue on another pi on the same net.  Can't ping or connect via ssh, VPN, VNC from outside the local WiFi network when eth0 and wlan0 are both connected.  Just FYI for others who might set this up.  Works perfectly for the purpose intended though.

Nice piece of work for a handful of likely users.  Thanks.

Kevin
